# Generated by Django 4.2.5 on 2024-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
