# Generated by Django 4.2.5 on 2024-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailybook', '0002_entry_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_modified',
        ),
    ]
