# Generated by Django 4.2.5 on 2024-03-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailybook', '0004_remove_dailybook_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailybook',
            old_name='date_created',
            new_name='note_date',
        ),
    ]
