# Generated by Django 4.2.5 on 2024-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailybook', '0006_remove_dailybook_note_date_dailybook_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybook',
            name='date_edit',
            field=models.DateTimeField(default='2022-10-02'),
            preserve_default=False,
        ),
    ]
