# Generated by Django 4.2.5 on 2024-03-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailybook', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
